#
# Application Routes
####################
#
# Here is where you can register all of the routes for your application.
#
#

default:
  method: GET
  path: /[{test}]
  controller: Example::ExampleController::index
  middlewares: Example::ExampleMiddleware::handler