#
# Application Routes
####################
#
# Here is where you can register all of the routes for your application.
#
#

default:
  method: GET
  path: /[{test}]
  controller:
    class: TestController
    method: index
  middlewares: [TestMiddleware]
